### ISSUE TITLE
MacOS amd64 CI backend test failures

### ISSUE THREAD

**Issue by sorenlassen** [onnx/onnx-mlir#1931]
see e.g. [this CI failure](https://github.com/onnx/onnx-mlir/actions/runs/3736355141/jobs/6340572095#step:11:8787)

```
======================================================================
ERROR: test_abs_cpu (__main__.OnnxBackendNodeModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/onnx/backend/test/runner/__init__.py", line 259, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/Users/runner/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/onnx/backend/test/runner/__init__.py", line 315, in run
    self.assert_similar_outputs(ref_outputs, outputs,
  File "/Users/runner/work/onnx-mlir/onnx-mlir/build/test/backend/Debug/inference_backend.py", line 1173, in assert_similar_outputs
    super(InferenceBackendTest, cls).assert_similar_outputs(ref_outputs, outputs, rtol, atol)
  File "/Users/runner/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/onnx/backend/test/runner/__init__.py", line 181, in assert_similar_outputs
    if ref_outputs[i].dtype == np.object:
  File "/Users/runner/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'object'
```
...
```
======================================================================
ERROR: test_vgg19_cpu (__main__.OnnxBackendRealModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/onnx/backend/test/runner/__init__.py", line 259, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/Users/runner/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/onnx/backend/test/runner/__init__.py", line 299, in run
    self.assert_similar_outputs(ref_outputs, outputs,
  File "/Users/runner/work/onnx-mlir/onnx-mlir/build/test/backend/Debug/inference_backend.py", line 1173, in assert_similar_outputs
    super(InferenceBackendTest, cls).assert_similar_outputs(ref_outputs, outputs, rtol, atol)
  File "/Users/runner/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/onnx/backend/test/runner/__init__.py", line 181, in assert_similar_outputs
    if ref_outputs[i].dtype == np.object:
  File "/Users/runner/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'object'

----------------------------------------------------------------------
Ran 2162 tests in 825.400s

FAILED (errors=459, skipped=1703)
```

**Comment by gongsu832** [comment]
For a successful builld:
```
Collecting numpy>=1.16.6
  Downloading numpy-1.23.5-cp310-cp310-macosx_10_9_x86_64.whl (18.1 MB)
```
For a failed build:
```
Collecting numpy>=1.16.6
  Downloading numpy-1.24.0-cp310-cp310-macosx_10_9_x86_64.whl (19.8 MB)
```
Sound like latest numpy has incompatible changes.

**Comment by gongsu832** [comment]
We could preinstall numpy 1.23 so onnx wouldn't try to install 1.24. The MacOS github action build is very cumbersome to manage because we can't get onto the VM on the server to try things out (there might be some hacky way to get on the VM but I never had the cycles to actually try). Everything is done through modifying the action script in a trial and error fashion, which is very tedious and time consuming.

**Comment by AlexandreEichenberger** [comment]
resolved?
