### ISSUE TITLE
Test failed for LSTM with peepholes

### ISSUE THREAD

**Issue by tungld** [onnx/onnx-mlir#242]
This is the second time we see the following error. Though it is a bit hard to reproduce the error, we need to find the root cause. @tungld will look at this problem. 

```
FAIL: test_lstm_with_peepholes_cpu (__main__.OnnxBackendNodeModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/onnx-mlir/third_party/onnx/onnx/backend/test/runner/__init__.py", line 248, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/home/circleci/project/onnx-mlir/third_party/onnx/onnx/backend/test/runner/__init__.py", line 311, in run
    self.assert_similar_outputs(ref_outputs, outputs,
  File "/home/circleci/project/onnx-mlir/third_party/onnx/onnx/backend/test/runner/__init__.py", line 174, in assert_similar_outputs
    np.testing.assert_allclose(
  File "/usr/local/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/usr/local/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 764, in assert_array_compare
    flagged = func_assert_same_pos(x, y, func=isnan, hasval='nan')
  File "/usr/local/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 740, in func_assert_same_pos
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=1e-07

x and y nan location mismatch:
 x: array([[[0.375069, 0.375069, 0.375069],
        [0.680131, 0.680131, 0.680131]]], dtype=float32)
 y: array([[[0.375069, 0.375069,      nan],
        [0.680131, 0.680131,      nan]]], dtype=float32)

----------------------------------------------------------------------
```

**Comment by doru1004** [comment]
@tungld any updates on this issue?

**Comment by tungld** [comment]
No updates, but I hope PR #367 is relevant. Let me observe this issue for a while once PR #367 is merged.

**Comment by tungld** [comment]
There has been no errors with peepholes since then. Close this.
