### ISSUE TITLE
Segmentation fault generating add.so when building

### ISSUE THREAD

**Issue by roastduck** [onnx/onnx-mlir#451]
The default building flow generates `add.so` as a test after `bin/onnx-mlir` is built. However, it runs into a segmentation fault as the following log from `make VERBOSE=1`:
```
[100%] Generating add.so
cd /home/rd/src/onnx-mlir/build/test/unit/Runtime/DocExampleTest && ../../../../bin/onnx-mlir /home/rd/src/onnx-mlir/build/test/unit/Runtime/DocExampleTest/add.onnx
Segmentation fault (core dumped)
test/unit/Runtime/DocExampleTest/CMakeFiles/OMCopyAndRename.dir/build.make:60: recipe for target 'test/unit/Runtime/DocExampleTest/add.so' failed
make[2]: *** [test/unit/Runtime/DocExampleTest/add.so] Error 139
make[2]: Leaving directory '/home/rd/src/onnx-mlir/build'
CMakeFiles/Makefile2:5106: recipe for target 'test/unit/Runtime/DocExampleTest/CMakeFiles/OMCopyAndRename.dir/all' failed
make[1]: *** [test/unit/Runtime/DocExampleTest/CMakeFiles/OMCopyAndRename.dir/all] Error 2
make[1]: Leaving directory '/home/rd/src/onnx-mlir/build'
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

GDB suggests it crash at the following line:

```
Program received signal SIGSEGV, Segmentation fault.
llvm::dyn_cast_or_null<mlir::ConstantOp, mlir::Operation> (Val=0x83481972fe388348)
    at /home/rd/install/llvm-project/llvm/include/llvm/Support/Casting.h:368
368       return (Val && isa<X>(Val)) ? cast<X>(Val) : nullptr;
(gdb) p Val
$1 = (mlir::Operation *) 0x83481972fe388348
```

Valgrind suggests there may be a free / delete / delete[] mismatch problem (no idea why Valgrind cannot find the debug symbols):

```
==71676== Memcheck, a memory error detector
==71676== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==71676== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==71676== Command: ../../../../bin/onnx-mlir /home/rd/src/onnx-mlir/build/test/unit/Runtime/DocExampleTest/add.onnx
==71676==
==71676== Mismatched free() / delete / delete []
==71676==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==71676==    by 0x9C7C41: ??? (in /home/rd/src/onnx-mlir/build/bin/onnx-mlir)
==71676==    by 0xDBC911: ??? (in /home/rd/src/onnx-mlir/build/bin/onnx-mlir)
==71676==    by 0x68FB47F: ???
==71676==    by 0xDB5D92: ??? (in /home/rd/src/onnx-mlir/build/bin/onnx-mlir)
==71676==    by 0x68FB4DF: ???
==71676==    by 0x1: ???
==71676==    by 0xFFEFEC3FF: ???
==71676==    by 0x400000001: ???
==71676==    by 0x69784C5: ???
==71676==    by 0x6978525: ???
==71676==    by 0x697787F: ???
==71676==  Address 0x697dde0 is 0 bytes inside a block of size 208 alloc'd
==71676==    at 0x4C2E0EF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==71676==    by 0x9C8014: ??? (in /home/rd/src/onnx-mlir/build/bin/onnx-mlir)
==71676==    by 0x697DD9F: ???
==71676==    by 0xF: ???
==71676==    by 0xFFEFEBE1F: ???
==71676==    by 0x697C261: ???
==71676==    by 0x697C25F: ???
==71676==
==71676== Use of uninitialised value of size 8
==71676==    at 0x9AAC2B: ??? (in /home/rd/src/onnx-mlir/build/bin/onnx-mlir)
==71676==
==71676== Use of uninitialised value of size 8
==71676==    at 0x9B3838: ??? (in /home/rd/src/onnx-mlir/build/bin/onnx-mlir)
==71676==    by 0x698676F: ???
==71676==    by 0xD37578: ??? (in /home/rd/src/onnx-mlir/build/bin/onnx-mlir)
==71676==
==71676== Use of uninitialised value of size 8
==71676==    at 0x9B3007: ??? (in /home/rd/src/onnx-mlir/build/bin/onnx-mlir)
==71676==    by 0x9B384C: ??? (in /home/rd/src/onnx-mlir/build/bin/onnx-mlir)
==71676==    by 0x698676F: ???
==71676==    by 0xDB5D92: ??? (in /home/rd/src/onnx-mlir/build/bin/onnx-mlir)
==71676==
==71676== Invalid read of size 8
==71676==    at 0x9AAA02: ??? (in /home/rd/src/onnx-mlir/build/bin/onnx-mlir)
==71676==    by 0x3FFFFFFFF: ???
==71676==    by 0x6979B57: ???
==71676==    by 0x6979B57: ???
==71676==    by 0x6979B4F: ???
==71676==    by 0xFFEFEC03F: ???
==71676==    by 0x3FFFFFFFF: ???
==71676==    by 0x6979B4F: ???
==71676==    by 0x6979B4F: ???
==71676==    by 0x6979B57: ???
==71676==    by 0x6979B4F: ???
==71676==    by 0xFFEFEC73F: ???
==71676==  Address 0x83481972fe388380 is not stack'd, malloc'd or (recently) free'd
==71676==
==71676==
==71676== Process terminating with default action of signal 11 (SIGSEGV)
==71676==  General Protection Fault
==71676==    at 0x9AAA02: ??? (in /home/rd/src/onnx-mlir/build/bin/onnx-mlir)
==71676==    by 0x3FFFFFFFF: ???
==71676==    by 0x6979B57: ???
==71676==    by 0x6979B57: ???
==71676==    by 0x6979B4F: ???
==71676==    by 0xFFEFEC03F: ???
==71676==    by 0x3FFFFFFFF: ???
==71676==    by 0x6979B4F: ???
==71676==    by 0x6979B4F: ???
==71676==    by 0x6979B57: ???
==71676==    by 0x6979B4F: ???
==71676==    by 0xFFEFEC73F: ???
==71676==
==71676== HEAP SUMMARY:
==71676==     in use at exit: 623,718 bytes in 3,223 blocks
==71676==   total heap usage: 6,890 allocs, 3,667 frees, 1,086,774 bytes allocated
==71676==
==71676== LEAK SUMMARY:
==71676==    definitely lost: 0 bytes in 0 blocks
==71676==    indirectly lost: 0 bytes in 0 blocks
==71676==      possibly lost: 96 bytes in 4 blocks
==71676==    still reachable: 623,622 bytes in 3,219 blocks
==71676==         suppressed: 0 bytes in 0 blocks
==71676== Rerun with --leak-check=full to see details of leaked memory
==71676==
==71676== For counts of detected and suppressed errors, rerun with: -v
==71676== Use --track-origins=yes to see where uninitialised values come from
==71676== ERROR SUMMARY: 5 errors from 5 contexts (suppressed: 0 from 0)
```

Running with the latest commit 4e0befdeee8894c2340ffb28c5fbbb332c0c5ef8, on Ubuntu 16.04.4.

Dependancies:

```
-- LLVM_PROJ_SRC           : /home/rd/install/llvm-project/
-- LLVM_PROJ_BUILD         : /home/rd/install/llvm-project/build
-- LLVM_PROJECT_LIB        : /home/rd/install/llvm-project/build/lib
-- LLVM_PROJ_BIN           : /home/rd/install/llvm-project/build/bin
-- ONNX_MLIR_TOOLS_DIR     : /home/rd/src/onnx-mlir/build/bin
-- CMAKE_INSTALL_PREFIX    : /usr/local
-- BUILD_SHARED_LIBS       : OFF
Generated: /home/rd/src/onnx-mlir/build/third_party/onnx/onnx/onnx-ml.proto
Generated: /home/rd/src/onnx-mlir/build/third_party/onnx/onnx/onnx-operators-ml.proto
--
-- ******** Summary ********
--   CMake version         : 3.16.2
--   CMake command         : /home/rd/install/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.3.0/cmake-3.16.2-hykvdre42igssl6maopjfd5s3ccm3bvr/bin/cmake
--   System                : Linux
--   C++ compiler          : /opt/gcc-7.3.0/bin/g++
--   C++ compiler version  : 7.3.0
--   CXX flags             :  -Wnon-virtual-dtor
--   Build type            : RelWithDebInfo
--   Compile definitions   :
--   CMAKE_PREFIX_PATH     :
--   CMAKE_INSTALL_PREFIX  : /usr/local
--   CMAKE_MODULE_PATH     : /home/rd/install/llvm-project/build/lib/cmake/llvm
--
--   ONNX version          : 1.7.0
--   ONNX NAMESPACE        : onnx
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--   ONNXIFI_ENABLE_EXT    : OFF
--
--   Protobuf compiler     : /home/rd/install/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.3.0/protobuf-3.11.2-7byfv73ijj7pshpslovhcq2fyqleftf3/bin/protoc
--   Protobuf includes     : /home/rd/install/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.3.0/protobuf-3.11.2-7byfv73ijj7pshpslovhcq2fyqleftf3/include
--   Protobuf libraries    : /home/rd/install/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.3.0/protobuf-3.11.2-7byfv73ijj7pshpslovhcq2fyqleftf3/lib/libprotobuf.so
--   BUILD_ONNX_PYTHON     : OFF
-- Found PythonInterp: /home/rd/install/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.3.0/python-3.7.0-5vsakxo7t7c3jona2og2myyjwydkkg6c/bin/python (found version "3.7")
-- Failed to find LLVM FileCheck
-- git Version: v1.5.1-1302d2ce
-- Version: 1.5.1
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK -- success
-- pybind11 v2.4.dev4
-- incl dir/home/rd/src/onnx-mlir/third_party/onnx/home/rd/src/onnx-mlir/build/third_party/onnx
-- Found PythonInterp: /home/rd/install/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.3.0/python-3.7.0-5vsakxo7t7c3jona2og2myyjwydkkg6c/bin/python (found suitable version "3.7", minimum required is "3")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rd/src/onnx-mlir/build
```

**Comment by tjingrant** [comment]
@roastduck Thanks for your detailed analysis & report! Unfortunately, I was unable to reproduce this issue on Mac OS; the gdb output you provided is very helpful, and it'll be particularly useful if you can run `bt` to show me the full stack trace, if possible!

**Comment by roastduck** [comment]
> @roastduck Thanks for your detailed analysis & report! Unfortunately, I was unable to reproduce this issue on Mac OS; the gdb output you provided is very helpful, and it'll be particularly useful if you can run `bt` to show me the full stack trace, if possible!

```
(gdb) bt
#0  llvm::dyn_cast_or_null<mlir::ConstantOp, mlir::Operation> (Val=0x83481972fe388348)
    at /home/rd/install/llvm-project/llvm/include/llvm/Support/Casting.h:368
#1  mlir::Value::getDefiningOp<mlir::ConstantOp> (this=0x7ffffffe1e28)
    at /home/rd/install/llvm-project/mlir/include/mlir/IR/Value.h:129
#2  getIntegerLiteralFromValue (value=..., intLit=@0x7ffffffe1e88: 15317610)
    at /home/rd/src/onnx-mlir/src/Dialect/ONNX/ONNXOpsHelper.cpp:119
#3  0x00000000009b2012 in mlir::IndexExprImpl::initAsType (this=this@entry=0x2070170, newContext=..., val=...,
    newType=newType@entry=mlir::IndexExprType::Symbol) at /home/rd/src/onnx-mlir/src/Dialect/ONNX/IndexExpr.cpp:400
#4  0x00000000009b27a5 in mlir::IndexExprContext::createSymbolIndex (this=this@entry=0x7ffffffe2360, val=...)
    at /home/rd/src/onnx-mlir/src/Dialect/ONNX/IndexExpr.cpp:130
#5  0x00000000009b3858 in mlir::IndexExprContext::createSymbolIndexFromParentContext (this=this@entry=0x7ffffffe2360,
    parentIndexExpr=...) at /home/rd/src/onnx-mlir/src/Dialect/ONNX/IndexExpr.cpp:199
#6  0x00000000009aac41 in ONNXOpBroadcastedShapeHelper::GetAccessExprs (this=this@entry=0x7ffffffe24a0, outerContext=...,
    operand=..., operandIndex=operandIndex@entry=0, outputAccessExprs=..., operandAccessExprs=...)
    at /home/rd/src/onnx-mlir/src/Dialect/ONNX/ONNXShapeHelper.cpp:139
#7  0x0000000000a013e2 in ONNXElementwiseVariadicOpLowering<mlir::ONNXAddOp>::matchAndRewrite (this=<optimized out>, op=0x2055cd0,
    operands=..., rewriter=...) at /home/rd/src/onnx-mlir/src/Conversion/ONNXToKrnl/Math/Elementwise.cpp:701
#8  0x0000000000dbc912 in mlir::ConversionPattern::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&) const ()
#9  0x0000000000f3c31b in mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::RewritePattern const&, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<mlir::LogicalResult (mlir::Pattern const&)>) ()
#10 0x0000000000f3c5ff in mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<mlir::LogicalResult (mlir::Pattern const&)>) ()
#11 0x0000000000dc2e32 in (anonymous namespace)::OperationLegalizer::legalize(mlir::Operation*, mlir::ConversionPatternRewriter&) ()
#12 0x0000000000dc5b29 in (anonymous namespace)::OperationConverter::convertOperations(llvm::ArrayRef<mlir::Operation*>) ()
#13 0x0000000000dc7f71 in mlir::applyPartialConversion(llvm::ArrayRef<mlir::Operation*>, mlir::ConversionTarget&, mlir::FrozenRewritePatternList const&, llvm::DenseSet<mlir::Operation*, llvm::DenseMapInfo<mlir::Operation*> >*) ()
#14 0x0000000000dc8081 in mlir::applyPartialConversion(mlir::Operation*, mlir::ConversionTarget&, mlir::FrozenRewritePatternList const&, llvm::DenseSet<mlir::Operation*, llvm::DenseMapInfo<mlir::Operation*> >*) ()
#15 0x00000000009dffe6 in (anonymous namespace)::FrontendToKrnlLoweringPass::runOnOperation (this=0x203ccc0)
    at /home/rd/src/onnx-mlir/src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp:143
#16 0x0000000000d7d661 in mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool) ()
#17 0x0000000000d7d891 in mlir::detail::OpToOpPassAdaptor::runPipeline(llvm::iterator_range<llvm::pointee_iterator<std::unique_ptr<mlir::Pass, std::default_delete<mlir::Pass> >*, mlir::Pass> >, mlir::Operation*, mlir::AnalysisManager, bool) ()
#18 0x0000000000d80479 in mlir::PassManager::run(mlir::ModuleOp) ()
--Type <RET> for more, q to quit, c to continue without paging--c
#19 0x00000000007eed26 in compileModule (module=..., context=..., outputBaseName=..., emissionTarget=emissionTarget@entry=EmitLib) at /home/rd/src/onnx-mlir/src/MainUtils.cpp:597
#20 0x00000000007d970c in main (argc=<optimized out>, argv=0x7ffffffe3d18) at /home/rd/src/onnx-mlir/src/main.cpp:57
```

**Comment by tjingrant** [comment]
Thanks, @roastduck I posted patch #455 which fixes the detected Valgrind errors.

**Comment by roastduck** [comment]
I failed to build that PR. It reports the following message during `make` (although the mssage is from CMake).

```
writing manifest file 'onnx.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running create_version
running cmake_build
CMake Error at /mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/cmake-3.17.3-3c4levwlugrpbsz2t3ba6t4nknqcnzh2/share/cmake-3.17/Modules/FindProtobuf.cmake:469 (file):
  file STRINGS file
  "/home/rd/install/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.3.0/protobuf-3.11.2-7byfv73ijj7pshpslovhcq2fyqleftf3/include/google/protobuf/stubs/common.h"
  cannot be read.
Call Stack (most recent call first):
  CMakeLists.txt:135 (find_package)


CMake Error at /mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/cmake-3.17.3-3c4levwlugrpbsz2t3ba6t4nknqcnzh2/share/cmake-3.17/Modules/FindProtobuf.cmake:475 (math):
  math cannot parse the expression: " / 1000000": syntax error, unexpected
  exp_DIVIDE (2).
Call Stack (most recent call first):
  CMakeLists.txt:135 (find_package)


CMake Error at /mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/cmake-3.17.3-3c4levwlugrpbsz2t3ba6t4nknqcnzh2/share/cmake-3.17/Modules/FindProtobuf.cmake:476 (math):
  math cannot parse the expression: " / 1000 % 1000": syntax error,
  unexpected exp_DIVIDE (2).
Call Stack (most recent call first):
  CMakeLists.txt:135 (find_package)


CMake Error at /mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/cmake-3.17.3-3c4levwlugrpbsz2t3ba6t4nknqcnzh2/share/cmake-3.17/Modules/FindProtobuf.cmake:477 (math):
  math cannot parse the expression: " % 1000": syntax error, unexpected
  exp_MOD (2).
Call Stack (most recent call first):
  CMakeLists.txt:135 (find_package)


Generated: /home/rd/src/onnx-mlir/third_party/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
Generated: /home/rd/src/onnx-mlir/third_party/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
CMake Warning at CMakeLists.txt:402 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11"
  (requested version 2.2) with any of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.


--
-- ******** Summary ********
--   CMake version         : 3.17.3
--   CMake command         : /mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/cmake-3.17.3-3c4levwlugrpbsz2t3ba6t4nknqcnzh2/bin/cmake
--   System                : Linux
--   C++ compiler          : /opt/gcc-7.3.0/bin/g++
--   C++ compiler version  : 7.3.0
--   CXX flags             :  -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   :
--   CMAKE_PREFIX_PATH     :
--   CMAKE_INSTALL_PREFIX  : /usr/local
--   CMAKE_MODULE_PATH     :
--
--   ONNX version          : 1.7.0
--   ONNX NAMESPACE        : onnx
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--   ONNXIFI_ENABLE_EXT    : OFF
--
--   Protobuf compiler     : /home/rd/install/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.3.0/protobuf-3.11.2-7byfv73ijj7pshpslovhcq2fyqleftf3/bin/protoc
--   Protobuf includes     : /home/rd/install/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.3.0/protobuf-3.11.2-7byfv73ijj7pshpslovhcq2fyqleftf3/include
--   Protobuf libraries    : /home/rd/install/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.3.0/protobuf-3.11.2-7byfv73ijj7pshpslovhcq2fyqleftf3/lib/libprotobuf.so
--   BUILD_ONNX_PYTHON     : ON
--     Python version      :
--     Python executable   : /mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/python-3.7.7-kjrtj4cbwtpd7wcspyejngjz77pzytwm/bin/python
--     Python includes     : /mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/python-3.7.7-kjrtj4cbwtpd7wcspyejngjz77pzytwm/include/python3.7m
-- Configuring incomplete, errors occurred!
See also "/home/rd/src/onnx-mlir/third_party/onnx/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
See also "/home/rd/src/onnx-mlir/third_party/onnx/.setuptools-cmake-build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 340, in <module>
    'backend-test-tools = onnx.backend.test.cmd_tools:main',
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/py-setuptools-46.1.3-d4bw3a66425kuapriy4rovv7jj5suslc/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/python-3.7.7-kjrtj4cbwtpd7wcspyejngjz77pzytwm/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/python-3.7.7-kjrtj4cbwtpd7wcspyejngjz77pzytwm/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/python-3.7.7-kjrtj4cbwtpd7wcspyejngjz77pzytwm/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/py-setuptools-46.1.3-d4bw3a66425kuapriy4rovv7jj5suslc/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/py-setuptools-46.1.3-d4bw3a66425kuapriy4rovv7jj5suslc/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/python-3.7.7-kjrtj4cbwtpd7wcspyejngjz77pzytwm/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/python-3.7.7-kjrtj4cbwtpd7wcspyejngjz77pzytwm/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/py-setuptools-46.1.3-d4bw3a66425kuapriy4rovv7jj5suslc/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 173, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/py-setuptools-46.1.3-d4bw3a66425kuapriy4rovv7jj5suslc/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 159, in call_command
    self.run_command(cmdname)
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/python-3.7.7-kjrtj4cbwtpd7wcspyejngjz77pzytwm/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/python-3.7.7-kjrtj4cbwtpd7wcspyejngjz77pzytwm/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/py-setuptools-46.1.3-d4bw3a66425kuapriy4rovv7jj5suslc/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/python-3.7.7-kjrtj4cbwtpd7wcspyejngjz77pzytwm/lib/python3.7/distutils/command/install_lib.py", line 105, in build
    self.run_command('build_py')
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/python-3.7.7-kjrtj4cbwtpd7wcspyejngjz77pzytwm/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/python-3.7.7-kjrtj4cbwtpd7wcspyejngjz77pzytwm/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 217, in run
    self.run_command('cmake_build')
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/python-3.7.7-kjrtj4cbwtpd7wcspyejngjz77pzytwm/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/python-3.7.7-kjrtj4cbwtpd7wcspyejngjz77pzytwm/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 203, in run
    subprocess.check_call(cmake_args)
  File "/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/python-3.7.7-kjrtj4cbwtpd7wcspyejngjz77pzytwm/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/cmake-3.17.3-3c4levwlugrpbsz2t3ba6t4nknqcnzh2/bin/cmake', '-DPYTHON_INCLUDE_DIR=/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/python-3.7.7-kjrtj4cbwtpd7wcspyejngjz77pzytwm/include/python3.7m', '-DPYTHON_EXECUTABLE=/mnt/ssd/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-7.3.0/python-3.7.7-kjrtj4cbwtpd7wcspyejngjz77pzytwm/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-37m-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/home/rd/src/onnx-mlir/third_party/onnx']' returned non-zero exit status 1.
test/unit/Runtime/DocExampleTest/CMakeFiles/OMInstallOnnx.dir/build.make:77: recipe for target 'test/unit/Runtime/DocExampleTest/CMakeFiles/OMInstallOnnx' failed
make[2]: *** [test/unit/Runtime/DocExampleTest/CMakeFiles/OMInstallOnnx] Error 1
CMakeFiles/Makefile2:5043: recipe for target 'test/unit/Runtime/DocExampleTest/CMakeFiles/OMInstallOnnx.dir/all' failed
make[1]: *** [test/unit/Runtime/DocExampleTest/CMakeFiles/OMInstallOnnx.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

I see the CI for this PR is failing. Maybe we should pass the CI first. Besides, I have upgraded my toolchains days ago, which can possibly be the cause.

**Comment by tjingrant** [comment]
Your failure seems to be coming from the installation of ONNX package, which may be flaky especially if installing from source (you can see that the build summary right before the build terminates was from `onnx`, not `onnx-mlir`).

Cleaning up toolchains and making sure up-to-date versions of dependent tools are appropriately installed seems to be the most straightforward next step. Here's an alternative if things don't work out:

You can try disabling the DocExampleTest unit test, which is one of a few targets within onnx-mlir that requires the onnx python package installation. To do so, commenting out this line would do:

https://github.com/onnx/onnx-mlir/blob/81c774ba5b1e715887a93f5ddbe421d11a924d0a/test/unit/Runtime/CMakeLists.txt#L1

Subsequently, try installing onnx from pypi by running `pip install onnx==1.7.0` (this step is only necessary if you wish to run the official onnx backend test suite). You can then proceed to build `onnx-mlir` as usual, all other tests should work with an external installation of onnx package.

> I see the CI for this PR is failing. Maybe we should pass the CI first. 

I'm aware of the CI failures and their causes, they were restricted to s390x architecture; it shouldn't impact x86-linux build.
