### ISSUE TITLE
Asserting s390x-ibm-linux cause a bug for test_scan9_sum_cpu

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#796]
When asserting `s390x-ibm-linux` in the backend test, we get an error for test_scan9_sum_cpu

To reproduce in the current master branch:
```
eichen@keytest:~/Onnxcode/onnx-mlir/build$ TEST_CASE_BY_USER=test_scan9_sum_cpu TEST_MTRIPLE=s390x-ibm-linux make check-onnx-backend
[  2%] Built target OMTensorUtils
...
[100%] Built target onnx-mlir
Test info:
  temporary results are in dir:./
  targeting triple: s390x-ibm-linux
...
test_scan9_sum
Shared library ./test_scan9_sum.so has been compiled.
/usr/local/lib/python3.8/dist-packages/onnx-1.7.0-py3.8-linux-s390x.egg/onnx/backend/test/runner/__init__.py:171: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if ref_outputs[i].dtype == np.object:

======================================================================
FAIL: test_scan9_sum_cpu (__main__.OnnxBackendNodeModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/onnx-1.7.0-py3.8-linux-s390x.egg/onnx/backend/test/runner/__init__.py", line 248, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/onnx-1.7.0-py3.8-linux-s390x.egg/onnx/backend/test/runner/__init__.py", line 311, in run
    self.assert_similar_outputs(ref_outputs, outputs,
  File "/usr/local/lib/python3.8/dist-packages/onnx-1.7.0-py3.8-linux-s390x.egg/onnx/backend/test/runner/__init__.py", line 174, in assert_similar_outputs
    np.testing.assert_allclose(
  File "/usr/local/lib/python3.8/dist-packages/numpy-1.20.0-py3.8-linux-s390x.egg/numpy/testing/_private/utils.py", line 1528, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/usr/local/lib/python3.8/dist-packages/numpy-1.20.0-py3.8-linux-s390x.egg/numpy/testing/_private/utils.py", line 842, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.001, atol=1e-07

Mismatched elements: 2 / 2 (100%)
Max absolute difference: 2.
Max relative difference: 0.2
 x: array([ 9., 12.], dtype=float32)
 y: array([11., 10.], dtype=float32)
```

I checked that the the option does not change the mlir files until llvm phase
```
eichen@keytest:~/Onnxcode/onnx-mlir/build/test/backend$ diff ~/atmp/stella/test_scan9_sum.input.mlir test_scan9_sum.input.mlir
eichen@keytest:~/Onnxcode/onnx-mlir/build/test/backend$ diff ~/atmp/stella/test_scan9_sum.llvm.mlir test_scan9_sum.llvm.mlir
```
 
@chentong319 @tungld didn't we have issues with the scan tests before already? I recalled that there were disabled for a bit.

Mind poking around to see what it is.

**Comment by tungld** [comment]
I saw this issue before, but did not catch it. Somehow the test passed.

**Comment by AlexandreEichenberger** [comment]
working now
